### ISSUE TITLE
[BUG] libcef.so Cannot allocate memory in static tls block

### ISSUE THREAD

**Issue by tkggusraqk** [jcefmaven/jcefmaven#71] opened 2023-03-19 10:55 UTC
**Describe the bug**
kylin os arm64,start error Cannot allocate memory in static tls block
**To Reproduce**
1. java -jar xxx.jar

**Expected behavior**

**Screenshots**

![kylin-arm64-error-jcef](https://user-images.githubusercontent.com/5164663/226170316-107ed911-1d55-481e-84f4-b28117dc3afc.png)

**Environment (please complete the following information):**
 - OS: linux
 - Architecture: arm64
 - Version:jcef-87476e9+cef-110.0.25+g75b1c96+chromium-110.0.5481.78

**Additional context**
Add any other context about the problem here

**Source code**
Add sources to reproduce the problem.
https://github.com/jcefmaven/jcefsampleapp

**Comment by FriwiDev** [comment] 2023-03-19 11:00
Duplicate of #70

**Closed** 2023-03-19 11:01 UTC
Labels: bug
